---
name: Wiki-Toolkit-Store-Mediawiki
version: !!perl/hash:Module::Build::Version
  original: 0.03
  version:
    - 0
    - 30
author:
  - 'Derek Price <derek@ximbiot.com>'
abstract: |-
  Mediawiki (MySQL) storage backend for
  Wiki::Toolkit
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 0
  Time::Piece::Adaptive: 0
  Time::Seconds: 0
  Wiki::Toolkit::Store::Database: 0
build_requires:
  Test::More: 0
provides:
  Wiki::Toolkit::Store::Mediawiki:
    file: lib/Wiki/Toolkit/Store/Mediawiki.pm
    version: 0.03
generated_by: Module::Build version 0.2804
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
